#pragma once
namespace degawong {

/* mat data type */
#define		DEGA_TYPE_NONE   		0x0000
#define		DEGA_TYPE_UCHAR8		0x0001
#define		DEGA_TYPE_SCHAR8		0x0002
#define		DEGA_TYPE_SINT16		0x0003
#define		DEGA_TYPE_USINT16		0x0004
#define		DEGA_TYPE_INT32 		0x0005
#define		DEGA_TYPE_FLOAT32		0x0006
#define		DEGA_TYPE_FLOAT64		0x0007
/* image format */
#define		DEGA_FORMAT_NONE		0x0000
#define		DEGA_FORMAT_GRAY		0x0001
#define		DEGA_FORMAT_BGR			0x0002
#define		DEGA_FORMAT_RGB			0x0003
#define		DEGA_FORMAT_RGBA		0x0004
#define		DEGA_FORMAT_BGRA		0x0005
#define		DEGA_FORMAT_ABGR		0x0006
#define		DEGA_FORMAT_ARGB		0x0007
#define		DEGA_FORMAT_NV12		0x0008
#define		DEGA_FORMAT_NV21		0x0009
#define		DEGA_FORMAT_YUYV		0x000a
#define		DEGA_FORMAT_YVYU		0x000b
/* mat data from where */
#define		DEGA_FROM_NONE  		0x0000
#define		DEGA_FROM_CLSNEW		0x0001
#define		DEGA_FROM_MALLOC		0x0002
#define		DEGA_FROM_CSTRUCT		0x0003
#define		DEGA_FROM_STBLOAD		0x0004
#define		DEGA_NO_DESTRUCTE		0x0005
/* make intergrate parameter */
#define     DEGA_MAKE_TYPE(depth, n) ((depth << 4) + n)
/* mat channel and data type */
#define		DEGA_TYPE_8UC1			DEGA_MAKE_TYPE(DEGA_TYPE_8U,(1))
#define		DEGA_TYPE_8UC2			DEGA_MAKE_TYPE(DEGA_TYPE_8U,(2))
#define		DEGA_TYPE_8UC3			DEGA_MAKE_TYPE(DEGA_TYPE_8U,(3))
#define		DEGA_TYPE_8UC4			DEGA_MAKE_TYPE(DEGA_TYPE_8U,(4))
#define		DEGA_TYPE_8UC(n)		DEGA_MAKE_TYPE(DEGA_TYPE_8U,(n))
/* mat channel and data type */
#define		DEGA_TYPE_8SUC1			DEGA_MAKE_TYPE(DEGA_TYPE_8S,(1))
#define		DEGA_TYPE_8SUC2			DEGA_MAKE_TYPE(DEGA_TYPE_8S,(2))
#define		DEGA_TYPE_8SUC3			DEGA_MAKE_TYPE(DEGA_TYPE_8S,(3))
#define		DEGA_TYPE_8SUC4			DEGA_MAKE_TYPE(DEGA_TYPE_8S,(4))
#define		DEGA_TYPE_8SC(n)		DEGA_MAKE_TYPE(DEGA_TYPE_8S,(n))
/* mat channel and data type */
#define		DEGA_TYPE_16UC1			DEGA_MAKE_TYPE(DEGA_TYPE_16U,(1))
#define		DEGA_TYPE_16UC2			DEGA_MAKE_TYPE(DEGA_TYPE_16U,(2))
#define		DEGA_TYPE_16UC3			DEGA_MAKE_TYPE(DEGA_TYPE_16U,(3))
#define		DEGA_TYPE_16UC4			DEGA_MAKE_TYPE(DEGA_TYPE_16U,(4))
#define		DEGA_TYPE_16UC(n)		DEGA_MAKE_TYPE(DEGA_TYPE_16U,(n))
/* image channel and data type */
#define		DEGA_TYPE_16SC1			DEGA_MAKE_TYPE(DEGA_TYPE_16S,(1))
#define		DEGA_TYPE_16SC2			DEGA_MAKE_TYPE(DEGA_TYPE_16S,(2))
#define		DEGA_TYPE_16SC3			DEGA_MAKE_TYPE(DEGA_TYPE_16S,(3))
#define		DEGA_TYPE_16SC4			DEGA_MAKE_TYPE(DEGA_TYPE_16S,(4))
#define		DEGA_TYPE_16SC(n)		DEGA_MAKE_TYPE(DEGA_TYPE_16S,(n))
/* mat channel and data type */
#define		DEGA_TYPE_32SC1			DEGA_MAKE_TYPE(DEGA_TYPE_32S,(1))
#define		DEGA_TYPE_32SC2			DEGA_MAKE_TYPE(DEGA_TYPE_32S,(2))
#define		DEGA_TYPE_32SC3			DEGA_MAKE_TYPE(DEGA_TYPE_32S,(3))
#define		DEGA_TYPE_32SC4			DEGA_MAKE_TYPE(DEGA_TYPE_32S,(4))
#define		DEGA_TYPE_32SC(n)		DEGA_MAKE_TYPE(DEGA_TYPE_32S,(n))
/* mat channel and data type */
#define		DEGA_TYPE_32FC1			DEGA_MAKE_TYPE(DEGA_TYPE_32F,(1))
#define		DEGA_TYPE_32FC2			DEGA_MAKE_TYPE(DEGA_TYPE_32F,(2))
#define		DEGA_TYPE_32FC3			DEGA_MAKE_TYPE(DEGA_TYPE_32F,(3))
#define		DEGA_TYPE_32FC4			DEGA_MAKE_TYPE(DEGA_TYPE_32F,(4))
#define		DEGA_TYPE_32FC(n)		DEGA_MAKE_TYPE(DEGA_TYPE_32F,(n))
/* mat channel and data type */
#define		DEGA_TYPE_64FC1			DEGA_MAKE_TYPE(DEGA_TYPE_64F,(1))
#define		DEGA_TYPE_64FC2			DEGA_MAKE_TYPE(DEGA_TYPE_64F,(2))
#define		DEGA_TYPE_64FC3			DEGA_MAKE_TYPE(DEGA_TYPE_64F,(3))
#define		DEGA_TYPE_64FC4			DEGA_MAKE_TYPE(DEGA_TYPE_64F,(4))
#define		DEGA_TYPE_64FC(n)		DEGA_MAKE_TYPE(DEGA_TYPE_64F,(n))

}